import type { Database } from './types';

export const INITIAL_DATA: Omit<Database, 'passcode'> = {
  students: [
    { id: 's1', firstName: 'Alice', lastName: 'Johnson', nfcId: '100', points: 150, classId: 'c1', history: [{ desc: 'Redeemed: Cool Pencil', amount: -50, date: Date.now() - 86400000 * 5 }, { desc: 'Redeemed coupon: GOOD-100', amount: 200, date: Date.now() - 86400000 * 10 }] },
    { id: 's2', firstName: 'Bob', lastName: 'Williams', nfcId: '101', points: 275, classId: 'c1', history: [] },
    { id: 's3', firstName: 'Charlie', lastName: 'Brown', nfcId: '102', points: 80, classId: 'c2', history: [] },
    { id: 's4', firstName: 'Diana', lastName: 'Miller', nfcId: '103', points: 1200, classId: 'c2', history: [{ desc: 'Redeemed: Ice Cream Coupon', amount: -1000, date: Date.now() - 86400000 * 2 }] },
    { id: 's5', firstName: 'Ethan', lastName: 'Davis', nfcId: '104', points: 450, classId: 'c3', history: [] },
    { id: 's6', firstName: 'Fiona', lastName: 'Garcia', nfcId: '105', points: 620, classId: 'c3', history: [] },
    { id: 's7', firstName: 'George', lastName: 'Rodriguez', nfcId: '106', points: 95, classId: 'c4', history: [] },
    { id: 's8', firstName: 'Hannah', lastName: 'Wilson', nfcId: '107', points: 180, classId: 'c4', history: [] },
    { id: 's9', firstName: 'Ian', lastName: 'Martinez', nfcId: '108', points: 320, classId: 'c5', history: [] },
    { id: 's10', firstName: 'Jasmine', lastName: 'Hernandez', nfcId: '109', points: 2100, classId: 'c5', history: [{ desc: 'Redeemed: Pizza Party Slice', amount: -2500, date: Date.now() - 86400000 * 15 }] },
    { id: 's11', firstName: 'Kevin', lastName: 'Lopez', nfcId: '110', points: 500, classId: 'c6', history: [] },
    { id: 's12', firstName: 'Laura', lastName: 'Gonzalez', nfcId: '111', points: 750, classId: 'c6', history: [] },
    { id: 's13', firstName: 'Mason', lastName: 'Perez', nfcId: '112', points: 110, classId: 'c1', history: [] },
    { id: 's14', firstName: 'Nora', lastName: 'Sanchez', nfcId: '113', points: 400, classId: 'c2', history: [] },
    { id: 's15', firstName: 'Oscar', lastName: 'Ramirez', nfcId: '114', points: 900, classId: 'c3', history: [] },
  ],
  classes: [
    { id: 'c1', name: 'Grade 1' },
    { id: 'c2', name: 'Grade 2' },
    { id: 'c3', name: 'Grade 3' },
    { id: 'c4', name: 'Grade 4' },
    { id: 'c5', name: 'Grade 5' },
    { id: 'c6', name: 'Grade 6' },
  ],
  teachers: [
    { id: 't1', name: 'Mrs. Johnson' },
    { id: 't2', name: 'Mr. Smith' },
    { id: 't3', name: 'Ms. Davis' },
    { id: 't4', name: 'Mr. Wilson' },
  ],
  categories: [
    'Good Behavior',
    'Academic Achievement',
    'Helping Others',
    'Perfect Attendance',
    'General Reward',
    'Creativity',
    'Sportsmanship',
  ],
  coupons: [
    { code: 'REWARD-500', value: 500, category: 'Good Behavior', teacher: 'Mrs. Johnson', used: false, createdAt: Date.now(), description: 'For an outstanding display of classroom leadership.' },
    { code: 'ACAD-100', value: 100, category: 'Academic Achievement', teacher: 'Mr. Smith', used: true, createdAt: Date.now() - 86400000 * 7, usedBy: 'Diana Miller', usedAt: Date.now() - 86400000 * 2 },
    { code: 'HELP-25', value: 25, category: 'Helping Others', teacher: 'Ms. Davis', used: false, createdAt: Date.now() - 86400000 },
    { code: 'ATTEND-75', value: 75, category: 'Perfect Attendance', teacher: 'Admin', used: false, createdAt: Date.now() - 86400000 * 14 },
    { code: 'GEN-50', value: 50, category: 'General Reward', teacher: 'Mr. Wilson', used: true, createdAt: Date.now() - 86400000 * 3, usedBy: 'Ethan Davis', usedAt: Date.now() - 86400000 },
    { code: 'CREATE-200', value: 200, category: 'Creativity', teacher: 'Mrs. Johnson', used: false, createdAt: Date.now() - 86400000 * 4 },
    { code: 'SPORT-50', value: 50, category: 'Sportsmanship', teacher: 'Mr. Smith', used: false, createdAt: Date.now() - 86400000 * 6 },
  ],
  prizes: [
    { id: 'p1', name: 'Cool Pencil', points: 50, icon: 'Pencil', inStock: true },
    { id: 'p2', name: 'Sticker Pack', points: 100, icon: 'Sticker', inStock: true },
    { id: 'p3', name: 'Candy Bar', points: 150, icon: 'Candy', inStock: true },
    { id: 'p7', name: 'Bouncy Ball', points: 200, icon: 'Circle', inStock: true },
    { id: 'p4', name: 'Free Homework Pass', points: 500, icon: 'FileText', inStock: true },
    { id: 'p8', name: 'Toy Car', points: 750, icon: 'Car', inStock: false },
    { id: 'p5', name: 'Ice Cream Coupon', points: 1000, icon: 'IceCream', inStock: true },
    { id: 'p10', name: 'Extra Recess', points: 1500, icon: 'Play', inStock: true },
    { id: 'p6', name: 'Pizza Party Slice', points: 2500, icon: 'Pizza', inStock: true },
    { id: 'p9', name: 'Lunch with Teacher', points: 5000, icon: 'Sandwich', inStock: true },
  ],
  updatedAt: Date.now(),
};
