import type { Database } from './types';

export const SCHOOL_DATA: Omit<Database, 'passcode'> = {
  name: 'School ABC',
  students: [
    { id: 'ss1', firstName: 'Emily', lastName: 'Smith', nfcId: 's101', points: 150, classId: 'sc1', history: [{ desc: 'Bonus points for class participation', amount: 50, date: Date.now() - 86400000 * 2 }] },
    { id: 'ss2', firstName: 'Jacob', lastName: 'Johnson', nfcId: 's102', points: 200, classId: 'sc2', history: [{ desc: 'Extra credit for science fair project', amount: 100, date: Date.now() - 86400000 * 5 }] },
    { id: 'ss3', firstName: 'Sophia', lastName: 'Williams', nfcId: 's103', points: 75, classId: 'sc1', history: [{ desc: 'Perfect attendance award', amount: 75, date: Date.now() - 86400000 * 1 }] },
    { id: 'ss4', firstName: 'Michael', lastName: 'Brown', nfcId: 's104', points: 300, classId: 'sc3', history: [{ desc: 'Redeemed: Pizza party with friends', amount: -200, date: Date.now() - 86400000 * 10 }, { desc: 'A+ on history exam', amount: 500, date: Date.now() - 86400000 * 20 }] },
    { id: 'ss5', firstName: 'Emma', lastName: 'Jones', nfcId: 's105', points: 120, classId: 'sc2', history: [{ desc: 'Helping a classmate with homework', amount: 20, date: Date.now() - 86400000 * 3 }] },
    { id: 'ss6', firstName: 'William', lastName: 'Garcia', nfcId: 's106', points: 50, classId: 'sc1', history: [{ desc: 'Cleaned up the classroom', amount: 50, date: Date.now() - 86400000 * 8 }] },
    { id: 'ss7', firstName: 'Olivia', lastName: 'Miller', nfcId: 's107', points: 450, classId: 'sc3', history: [{ desc: 'Won the school spelling bee', amount: 450, date: Date.now() - 86400000 * 4 }] },
    { id: 'ss8', firstName: 'James', lastName: 'Davis', nfcId: 's108', points: 600, classId: 'sc2', history: [{ desc: 'Tutoring younger students', amount: 600, date: Date.now() - 86400000 * 12 }] },
    { id: 'ss9', firstName: 'Isabella', lastName: 'Rodriguez', nfcId: 's109', points: 180, classId: 'sc1', history: [{ desc: 'Designing the class bulletin board', amount: 180, date: Date.now() - 86400000 * 6 }] },
    { id: 'ss10', firstName: 'Alexander', lastName: 'Martinez', nfcId: 's110', points: 1000, classId: 'sc3', history: [{ desc: 'Redeemed: Principal for a day', amount: -1000, date: Date.now() - 86400000 * 15 }, { desc: 'Student of the month award', amount: 2000, date: Date.now() - 86400000 * 40 }] },
    { id: 'ss11', firstName: 'Mia', lastName: 'Hernandez', nfcId: 's111', points: 250, classId: 'sc4', history: [{ desc: 'Leading a school club', amount: 250, date: Date.now() - 86400000 * 7 }] },
    { id: 'ss12', firstName: 'Ethan', lastName: 'Lopez', nfcId: 's112', points: 350, classId: 'sc4', history: [{ desc: 'Organizing a charity drive', amount: 350, date: Date.now() - 86400000 * 14 }] },
    { id: 'ss13', firstName: 'Abigail', lastName: 'Wilson', nfcId: 's113', points: 175, classId: 'sc5', history: [{ desc: 'Submitted artwork to the school paper', amount: 175, date: Date.now() - 86400000 * 9 }] },
    { id: 'ss14', firstName: 'Benjamin', lastName: 'Anderson', nfcId: 's114', points: 220, classId: 'sc5', history: [{ desc: 'Perfect score on math quiz', amount: 220, date: Date.now() - 86400000 * 11 }] },
    { id: 'ss15', firstName: 'Charlotte', lastName: 'Thomas', nfcId: 's115', points: 85, classId: 'sc6', history: [{ desc: 'Volunteering in the library', amount: 85, date: Date.now() - 86400000 * 13 }] },
    { id: 'ss16', firstName: 'Daniel', lastName: 'Jackson', nfcId: 's116', points: 400, classId: 'sc6', history: [{ desc: 'Winning the science olympiad', amount: 400, date: Date.now() - 86400000 * 16 }] },
    { id: 'ss17', firstName: 'Harper', lastName: 'White', nfcId: 's117', points: 320, classId: 'sc7', history: [{ desc: 'Creating a presentation for the school assembly', amount: 320, date: Date.now() - 86400000 * 18 }] },
    { id: 'ss18', firstName: 'Henry', lastName: 'Harris', nfcId: 's118', points: 190, classId: 'sc7', history: [{ desc: 'Assisting the coach with team practice', amount: 190, date: Date.now() - 86400000 * 22 }] },
    { id: 'ss19', firstName: 'Evelyn', lastName: 'Martin', nfcId: 's119', points: 280, classId: 'sc8', history: [{ desc: 'Participating in the school play', amount: 280, date: Date.now() - 86400000 * 25 }] },
    { id: 'ss20', firstName: 'Jackson', lastName: 'Thompson', nfcId: 's120', points: 650, classId: 'sc8', history: [{ desc: 'Building a robot for the robotics club', amount: 650, date: Date.now() - 86400000 * 30 }] },
    { id: 'ss21', firstName: 'Avery', lastName: 'Moore', nfcId: 's121', points: 550, classId: 'sc1', history: [{ desc: 'Scored the winning goal in the soccer match', amount: 550, date: Date.now() - 86400000 * 28 }] },
    { id: 'ss22', firstName: 'David', lastName: 'Lee', nfcId: 's122', points: 210, classId: 'sc2', history: [{ desc: 'Wrote an article for the school newspaper', amount: 210, date: Date.now() - 86400000 * 35 }] },
    { id: 'ss23', firstName: 'Scarlett', lastName: 'Perez', nfcId: 's123', points: 480, classId: 'sc3', history: [{ desc: 'First place in the debate competition', amount: 480, date: Date.now() - 86400000 * 45 }] },
    { id: 'ss24', firstName: 'Joseph', lastName: 'Gonzalez', nfcId: 's124', points: 330, classId: 'sc4', history: [{ desc: 'Composed a song for the school band', amount: 330, date: Date.now() - 86400000 * 50 }] },
    { id: 'ss25', firstName: 'Victoria', lastName: 'Clark', nfcId: 's125', points: 700, classId: 'sc5', history: [{ desc: 'Developed a mobile app for a school project', amount: 700, date: Date.now() - 86400000 * 60 }] },
    { id: 'ss26', firstName: 'Samuel', lastName: 'Lewis', nfcId: 's126', points: 270, classId: 'sc6', history: [{ desc: 'Mentoring a new student', amount: 270, date: Date.now() - 86400000 * 17 }] },
    { id: 'ss27', firstName: 'Grace', lastName: 'Robinson', nfcId: 's127', points: 430, classId: 'sc7', history: [{ desc: 'Organized a school-wide coding competition', amount: 430, date: Date.now() - 86400000 * 23 }] },
  ],
  classes: [
    { id: 'sc1', name: 'Grade 5' },
    { id: 'sc2', name: 'Grade 6' },
    { id: 'sc3', name: 'Grade 7' },
    { id: 'sc4', name: 'Grade 8' },
    { id: 'sc5', name: 'Grade 9' },
    { id: 'sc6', name: 'Grade 10' },
    { id: 'sc7', name: 'Grade 11' },
    { id: 'sc8', name: 'Grade 12' },
  ],
  teachers: [
    { id: 'st1', name: 'Mr. Smith' },
    { id: 'st2', name: 'Mrs. Jones' },
    { id: 'st3', name: 'Ms. Davis' },
    { id: 'st4', name: 'Mr. Brown' },
    { id: 'st5', name: 'Mr. Wilson' },
    { id: 'st6', name: 'Mrs. Anderson' },
    { id: 'st7', name: 'Ms. Thomas' },
    { id: 'st8', name: 'Mr. Jackson' },
  ],
  categories: [
    'Academics',
    'Good Behavior',
    'Helping Others',
    'School Spirit',
    'Attendance',
    'Extra Curricular',
    'Creativity',
    'Leadership',
    'Teamwork',
    'Problem Solving',
  ],
  coupons: [
    { code: 'ACAD10', category: 'Academics', value: 10, used: false, usedBy: null, usedAt: null, createdAt: Date.now() - 86400000 * 20 },
    { code: 'BEHAVE5', category: 'Good Behavior', value: 5, used: true, usedBy: 'Emily Smith', usedAt: Date.now() - 86400000 * 2, createdAt: Date.now() - 86400000 * 30 },
    { code: 'HELP15', category: 'Helping Others', value: 15, used: false, usedBy: null, usedAt: null, createdAt: Date.now() - 86400000 * 10 },
    { code: 'SPIRIT20', category: 'School Spirit', value: 20, used: false, usedBy: null, usedAt: null, createdAt: Date.now() - 86400000 * 5 },
    { code: 'ATTEND25', category: 'Attendance', value: 25, used: true, usedBy: 'Michael Brown', usedAt: Date.now() - 86400000 * 1, createdAt: Date.now() - 86400000 * 40 },
    { code: 'EXTRA30', category: 'Extra Curricular', value: 30, used: false, usedBy: null, usedAt: null, createdAt: Date.now() - 86400000 * 15 },
    { code: 'CREATE35', category: 'Creativity', value: 35, used: false, usedBy: null, usedAt: null, createdAt: Date.now() - 86400000 * 25 },
    { code: 'LEAD40', category: 'Leadership', value: 40, used: true, usedBy: 'Mia Hernandez', usedAt: Date.now() - 86400000 * 7, createdAt: Date.now() - 86400000 * 50 },
    { code: 'TEAM45', category: 'Teamwork', value: 45, used: false, usedBy: null, usedAt: null, createdAt: Date.now() - 86400000 * 3 },
    { code: 'SOLVE50', category: 'Problem Solving', value: 50, used: false, usedBy: null, usedAt: null, createdAt: Date.now() - 86400000 * 12 },
  ],
  prizes: [
    { id: 'sp1', name: 'Sticker Pack', points: 50, icon: 'SmilingFace', inStock: true },
    { id: 'sp2', name: 'Homework Pass', points: 100, icon: 'Scroll', inStock: true },
    { id: 'sp3', name: 'Pizza Slice', points: 200, icon: 'Pizza', inStock: true },
    { id: 'sp4', name: 'Movie Ticket', points: 500, icon: 'Ticket', inStock: true },
    { id: 'sp5', name: 'T-Shirt', points: 750, icon: 'Shirt', inStock: true },
    { id: 'sp6', name: 'Gift Card', points: 1000, icon: 'Gift', inStock: true },
    { id: 'sp7', name: 'Tablet', points: 5000, icon: 'Tablet', inStock: false },
    { id: 'sp8', name: 'Laptop', points: 10000, icon: 'Laptop', inStock: false },
  ],
  updatedAt: Date.now(),
};
