import type { Database } from './types';

export const YESHIVA_DATA: Omit<Database, 'passcode'> = {
  name: 'Yeshiva',
  students: [
    { id: '100', firstName: 'Shmuel', lastName: 'Goldstein', nfcId: '100', points: 120, classId: 'yc1' },
    { id: '101', firstName: 'Avi', lastName: 'Schwartz', nfcId: '101', points: 80, classId: 'yc2' },
    { id: '102', firstName: 'Yosef', lastName: 'Cohen', nfcId: '102', points: 250, classId: 'yc1' },
    { id: '103', firstName: 'David', lastName: 'Levi', nfcId: '103', points: 400, classId: 'yc3' },
    { id: '104', firstName: 'Moshe', lastName: 'Katz', nfcId: '104', points: 150, classId: 'yc2' },
    { id: '105', firstName: 'Dovid', lastName: 'Weiss', nfcId: '105', points: 300, classId: 'yc1' },
    { id: '106', firstName: 'Chaim', lastName: 'Friedman', nfcId: '106', points: 50, classId: 'yc3' },
    { id: '107', firstName: 'Yaakov', lastName: 'Rosenberg', nfcId: '107', points: 600, classId: 'yc2' },
    { id: '108', firstName: 'Yisrael', lastName: 'Adler', nfcId: '108', points: 180, classId: 'yc1' },
    { id: '109', firstName: 'Menachem', lastName: 'Gross', nfcId: '109', points: 1200, classId: 'yc3' },
    { id: '110', firstName: 'Eliezer', lastName: 'Klein', nfcId: '110', points: 220, classId: 'yc2' },
    { id: '111', firstName: 'Baruch', lastName: 'Stein', nfcId: '111', points: 70, classId: 'yc1' },
    { id: '112', firstName: 'Aryeh', lastName: 'Feldman', nfcId: '112', points: 350, classId: 'yc3' },
    { id: '113', firstName: 'Zev', lastName: 'Hoffman', nfcId: '113', points: 100, classId: 'yc2' },
    { id: '114', firstName: 'Tzvi', lastName: 'Roth', nfcId: '114', points: 800, classId: 'yc1' },
    { id: '115', firstName: 'Akiva', lastName: 'Berger', nfcId: '115', points: 190, classId: 'yc3' },
    { id: '116', firstName: 'Yehuda', lastName: 'Green', nfcId: '116', points: 40, classId: 'yc2' },
    { id: '117', firstName: 'Shlomo', lastName: 'Jacobs', nfcId: '117', points: 550, classId: 'yc1' },
    { id: '118', firstName: 'Gedalya', lastName: 'Fisher', nfcId: '118', points: 130, classId: 'yc3' },
    { id: '119', firstName: 'Nachman', lastName: 'Pollack', nfcId: '119', points: 1000, classId: 'yc2' },
    { id: '120', firstName: 'Daniel', lastName: 'Kaplan', nfcId: '120', points: 450, classId: 'yc4' },
    { id: '121', firstName: 'Ephraim', lastName: 'Shapiro', nfcId: '121', points: 280, classId: 'yc1' },
    { id: '122', firstName: 'Ezra', lastName: 'Silver', nfcId: '122', points: 90, classId: 'yc2' },
    { id: '123', firstName: 'Gavriel', lastName: 'Goldman', nfcId: '123', points: 720, classId: 'yc3' },
    { id: '124', firstName: 'Hershel', lastName: 'Mandel', nfcId: '124', points: 310, classId: 'yc4' },
    { id: '125', firstName: 'Levi', lastName: 'Stern', nfcId: '125', points: 1500, classId: 'yc1' },
    { id: '126', firstName: 'Mordechai', lastName: 'Blau', nfcId: '126', points: 400, classId: 'yc2' },
    { id: '127', firstName: 'Noach', lastName: 'Singer', nfcId: '127', points: 85, classId: 'yc3' },
    { id: '128', firstName: 'Reuven', lastName: 'Farkas', nfcId: '128', points: 110, classId: 'yc4' },
    { id: '129', firstName: 'Simcha', lastName: 'Teitelbaum', nfcId: '129', points: 2200, classId: 'yc1' },
    { id: '130', firstName: 'Yitzchak', lastName: 'Fishman', nfcId: '130', points: 50, classId: 'yc1' },
    { id: '131', firstName: 'Shraga', lastName: 'Meisels', nfcId: '131', points: 95, classId: 'yc2' },
    { id: '132', firstName: 'Naftali', lastName: 'Glick', nfcId: '132', points: 320, classId: 'yc3' },
    { id: '133', firstName: 'Benyamin', lastName: 'Schumer', nfcId: '133', points: 480, classId: 'yc4' },
    { id: '134', firstName: 'Eitan', lastName: 'Weissman', nfcId: '134', points: 160, classId: 'yc1' },
    { id: '135', firstName: 'Ilan', lastName: 'Rothman', nfcId: '135', points: 290, classId: 'yc2' },
    { id: '136', firstName: 'Meir', lastName: 'Silber', nfcId: '136', points: 65, classId: 'yc3' },
    { id: '137', firstName: 'Shimon', lastName: 'Neuman', nfcId: '137', points: 520, classId: 'yc4' },
    { id: '138', firstName: 'Yechiel', lastName: 'Landau', nfcId: '138', points: 170, classId: 'yc1' },
    { id: '139', firstName: 'Zalman', lastName: 'Goldberg', nfcId: '139', points: 950, classId: 'yc2' },
    { id: '140', firstName: 'Asher', lastName: 'Kornbluth', nfcId: '140', points: 210, classId: 'yc3' },
    { id: '141', firstName: 'Binyamin', lastName: 'Zimmerman', nfcId: '141', points: 430, classId: 'yc4' },
    { id: '142', firstName: 'Eliyahu', lastName: 'Wolfson', nfcId: '142', points: 140, classId: 'yc1' },
    { id: '143', firstName: 'Gershon', lastName: 'Braun', nfcId: '143', points: 30, classId: 'yc2' },
    { id: '144', firstName: 'Isser', lastName: 'Werner', nfcId: '144', points: 680, classId: 'yc3' },
    { id: '145', firstName: 'Mendel', lastName: 'Perlman', nfcId: '145', points: 260, classId: 'yc4' },
    { id: '146', firstName: 'Nechemia', lastName: 'Moskowitz', nfcId: '146', points: 180, classId: 'yc1' },
    { id: '147', firstName: 'Pinchas', lastName: 'Horowitz', nfcId: '147', points: 880, classId: 'yc2' },
    { id: '148', firstName: 'Shaya', lastName: 'Fischer', nfcId: '148', points: 390, classId: 'yc3' },
    { id: '149', firstName: 'Yonoson', lastName: 'Frankel', nfcId: '149', points: 1300, classId: 'yc4' },
    { id: '150', firstName: 'Refael', lastName: 'Cohen', nfcId: '150', points: 150, classId: 'yc1' },
    { id: '151', firstName: 'Shalom', lastName: 'Mizrachi', nfcId: '151', points: 250, classId: 'yc2' },
    { id: '152', firstName: 'Ovadia', lastName: 'Yosef', nfcId: '152', points: 400, classId: 'yc3' },
    { id: '153', firstName: 'Chacham', lastName: 'Shalom', nfcId: '153', points: 120, classId: 'yc1' },
    { id: '154', firstName: 'Ben Ish', lastName: 'Chai', nfcId: '154', points: 80, classId: 'yc2' },
  ],
  classes: [
    { id: 'yc1', name: 'Shiur Aleph' },
    { id: 'yc2', name: 'Shiur Bet' },
    { id: 'yc3', name: 'Shiur Gimmel' },
    { id: 'yc4', name: 'Bais Medrash' },
    { id: 'yc5', name: 'Kollel' },
  ],
  teachers: [
    { id: 'yt1', name: 'Rabbi Cohen', username: 'rabbicohen', passcode: '1234' },
    { id: 'yt2', name: 'Rabbi Levi', username: 'rabbilevi', passcode: '1234' },
    { id: 'yt3', name: 'Rav Goldberg', username: 'ravgoldberg', passcode: '1234' },
    { id: 'yt4', name: 'Rosh Yeshiva', username: 'roshyeshiva', passcode: '1234' },
    { id: 'yt5', name: 'Rabbi Epstein', username: 'rabbiepstein', passcode: '1234' },
  ],
  categories: [
    { id: 'ycat1', name: 'Middos Tovos', points: 100 },
    { id: 'ycat2', name: 'Shteiging', points: 50 },
    { id: 'ycat3', name: 'Gemara B\'iyun', points: 75 },
    { id: 'ycat4', name: 'Mishna Mastery', points: 40 },
    { id: 'ycat5', name: 'Tefillah', points: 10 },
    { id: 'ycat6', name: 'Chesed', points: 150 },
    { id: 'ycat7', name: 'Avos Ubanim', points: 25 },
    { id: 'ycat8', name: 'Chavrusa Learning', points: 20 },
  ],
  coupons: [
    { id: '101010', code: '101010', value: 10, category: 'Tefillah', teacher: 'Rabbi Cohen', used: false, createdAt: Date.now(), description: 'For excellent concentration during morning prayers.' },
    { id: '505050', code: '505050', value: 50, category: 'Shteiging', teacher: 'Rabbi Levi', used: false, createdAt: Date.now() - 86400000, description: 'For asking a great question in shiur.' },
    { id: '100100', code: '100100', value: 100, category: 'Gemara B\'iyun', teacher: 'Rav Goldberg', used: false, createdAt: Date.now() - 86400000 * 2, description: 'For preparing well for shiur.' },
    { id: '757575', code: '757575', value: 75, category: 'Mishna Mastery', teacher: 'Rabbi Cohen', used: false, createdAt: Date.now() - 86400000 * 3, description: 'For completing the weekly Mishna assignment.' },
    { id: '200200', code: '200200', value: 200, category: 'Middos Tovos', teacher: 'Rosh Yeshiva', used: false, createdAt: Date.now() - 86400000 * 4, description: 'For exceptional character and integrity.' },
    { id: '150150', code: '150150', value: 150, category: 'Chesed', teacher: 'Rabbi Levi', used: true, createdAt: Date.now() - 86400000 * 5, usedBy: '101', usedAt: Date.now() - 86400000 * 2 },
    { id: '100000', code: '100000', value: 100, category: 'Avos Ubanim', teacher: 'Admin', used: false, createdAt: Date.now() - 86400000 * 6, description: 'For attending Avos Ubanim learning program.' },
    { id: '500500', code: '500500', value: 50, category: 'Chavrusa Learning', teacher: 'Rabbi Epstein', used: false, createdAt: Date.now() - 86400000 * 7, description: 'For productive learning with a chavrusa.' },
    { id: '200001', code: '200001', value: 10, category: 'Tefillah', teacher: 'Rabbi Cohen', used: false, createdAt: Date.now(), description: 'For excellent concentration during morning prayers.' },
    { id: '200002', code: '200002', value: 50, category: 'Shteiging', teacher: 'Rabbi Levi', used: false, createdAt: Date.now(), description: 'For asking a great question in shiur.' },
    { id: '200003', code: '200003', value: 100, category: 'Gemara B\'iyun', teacher: 'Rav Goldberg', used: false, createdAt: Date.now(), description: 'For preparing well for shiur.' },
    { id: '200004', code: '200004', value: 75, category: 'Mishna Mastery', teacher: 'Rabbi Cohen', used: false, createdAt: Date.now(), description: 'For completing the weekly Mishna assignment.' },
    { id: '200005', code: '200005', value: 200, category: 'Middos Tovos', teacher: 'Rosh Yeshiva', used: false, createdAt: Date.now(), description: 'For exceptional character and integrity.' },
    { id: '200006', code: '200006', value: 150, category: 'Chesed', teacher: 'Rabbi Levi', used: false, createdAt: Date.now(), description: 'For helping another student.' },
    { id: '200007', code: '200007', value: 25, category: 'Avos Ubanim', teacher: 'Admin', used: false, createdAt: Date.now(), description: 'For attending Avos Ubanim learning program.' },
    { id: '200008', code: '200008', value: 20, category: 'Chavrusa Learning', teacher: 'Rabbi Epstein', used: false, createdAt: Date.now(), description: 'For productive learning with a chavrusa.' },
    { id: '200009', code: '200009', value: 10, category: 'Tefillah', teacher: 'Rabbi Cohen', used: false, createdAt: Date.now(), description: 'For excellent concentration during morning prayers.' },
    { id: '200010', code: '200010', value: 50, category: 'Shteiging', teacher: 'Rabbi Levi', used: false, createdAt: Date.now(), description: 'For asking a great question in shiur.' },
    { id: '200011', code: '200011', value: 100, category: 'Gemara B\'iyun', teacher: 'Rav Goldberg', used: false, createdAt: Date.now(), description: 'For preparing well for shiur.' },
    { id: '200012', code: '200012', value: 75, category: 'Mishna Mastery', teacher: 'Rabbi Cohen', used: false, createdAt: Date.now(), description: 'For completing the weekly Mishna assignment.' },
    { id: '200013', code: '200013', value: 200, category: 'Middos Tovos', teacher: 'Rosh Yeshiva', used: false, createdAt: Date.now(), description: 'For exceptional character and integrity.' },
    { id: '200014', code: '200014', value: 150, category: 'Chesed', teacher: 'Rabbi Levi', used: false, createdAt: Date.now(), description: 'For helping another student.' },
    { id: '200015', code: '200015', value: 25, category: 'Avos Ubanim', teacher: 'Admin', used: false, createdAt: Date.now(), description: 'For attending Avos Ubanim learning program.' },
    { id: '200016', code: '200016', value: 20, category: 'Chavrusa Learning', teacher: 'Rabbi Epstein', used: false, createdAt: Date.now(), description: 'For productive learning with a chavrusa.' },
    { id: '200017', code: '200017', value: 50, category: 'Shteiging', teacher: 'Rabbi Levi', used: false, createdAt: Date.now(), description: 'For asking a great question in shiur.' },
    { id: '200018', code: '200018', value: 100, category: 'Gemara B\'iyun', teacher: 'Rav Goldberg', used: false, createdAt: Date.now(), description: 'For preparing well for shiur.' },
    { id: '200019', code: '200019', value: 75, category: 'Mishna Mastery', teacher: 'Rabbi Cohen', used: false, createdAt: Date.now(), description: 'For completing the weekly Mishna assignment.' },
    { id: '200020', code: '200020', value: 200, category: 'Middos Tovos', teacher: 'Rosh Yeshiva', used: false, createdAt: Date.now(), description: 'For exceptional character and integrity.' },
  ],
  prizes: [
    { id: 'yp1', name: 'Small Sefer', points: 250, icon: 'BookOpen', inStock: true },
    { id: 'yp2', name: 'Candy from the Rebbe', points: 100, icon: 'Candy', inStock: true },
    { id: 'yp3', name: 'Pizza Slice', points: 500, icon: 'Pizza', inStock: true },
    { id: 'yp4', name: 'Large Sefer (Artscroll)', points: 1500, icon: 'BookMarked', inStock: true },
    { id: 'yp5', name: 'Day off from chores', points: 1000, icon: 'Home', inStock: true },
    { id: 'yp6', name: 'Ice Cream in town', points: 750, icon: 'IceCream', inStock: false },
    { id: 'yp7', name: 'Shabbos Guest for a Meal', points: 2000, icon: 'Users', inStock: true },
    { id: 'yp8', name: 'Seforim Gift Card', points: 3000, icon: 'Gift', inStock: true },
    { id: 'yp9', name: 'Trip with the Rebbe', points: 10000, icon: 'Bus', inStock: true },
  ],
  updatedAt: Date.now(),
};
